spring:
  application:
    name: zuul-gateway

server:
  port: 1101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

#动态加载过滤器的配置，将会在配置类中加载这些属性，用来初始化过滤器加载器
zuul:
  filter:
    root: filter #动态加载过滤器根路径
    interval: 5  #动态加载过滤器时间间隔 单位 秒